spring:
   profiles:
      active:
        - dev
---
server:
  port: 8081

spring:
  profiles: dev
  application:
      name: config-test-client5

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7001/eureka
  register-with-eureka: false

info:
  app.name: cloud-config-client-dev21993
  company.name: czz1993
---
server:
  port: 8082

spring:
  profiles: beta
  application:
      name: config-test-client5

eureka:
 client:
  serviceUrl:
    defaultZone: http://admin:admin@localhost:7001/eureka
  register-with-eureka: false
  
info:
  app.name: cloud-config-client-beta21993
  company.name: czz1993
